### ISSUE TITLE
Can't update scatterplot point color

### ISSUE THREAD

**Issue by heshan0131** [uber-common/deck.gl#24]
@ibgreen 
I have edited the example to duplicate my issue that point layer color won't update in this branch:
https://github.com/heshan0131/deck.gl/tree/performance-fix

**Comment by ibgreen** [comment]
@wwwtyro we seem to have an issue with buffer updates, great if you could take a peek.

**Comment by wwwtyro** [comment]
@ibgreen @heshan0131 Yes, looking right now.

**Comment by wwwtyro** [comment]
@ibgreen @heshan0131 Trying it out on this branch, it seems to work.

![screenshot from 2016-03-22 18-23-57](https://cloud.githubusercontent.com/assets/929443/13971128/91967750-f05b-11e5-8db0-a3e5d75de1cc.png)

The package.json is pointing to luma.gl v0.0.2. Is it possible an npm link is messing things up?

**Comment by heshan0131** [comment]
@wwwtyro you are right, upgrade to luma.gl 0.0.2 fixed the issue

**Comment by wwwtyro** [comment]
Excellent! :+1:
